In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 4, 7, 12])

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  4,  7, 12])

In [14]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [21]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [22]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n = np.array([[1,2,3],[2,3,4],[4,5,6]])
n

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [28]:
n[0,1] 

np.int64(2)

In [33]:
n[1] = [2.1, 2, 2]
n

array([[1, 2, 3],
       [2, 2, 2],
       [4, 5, 6]])

In [35]:
n[:,0]

array([1, 2, 4])

In [46]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [49]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [50]:
np.random.seed(2)
np.random.rand(5,2)*100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [51]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
a + 1 

array([1, 2, 3, 4, 5])

In [58]:
b = (10 + (a*2))**2 / 100

In [59]:
a + b 

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [60]:
a >= b

array([False, False,  True,  True,  True])

In [64]:
a[(a > b)]

array([2, 3, 4])

In [65]:
a.min()

np.int64(0)

In [66]:
a.max()

np.int64(4)

In [67]:
a.sum()

np.int64(10)

In [68]:
a.mean()

np.float64(2.0)

In [69]:
a.std()

np.float64(1.4142135623730951)